# Generated by Django 4.2 on 2023-05-10 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("conductoresApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modelo", models.CharField(max_length=4, verbose_name="Modelo")),
                (
                    "placa",
                    models.CharField(max_length=7, unique=True, verbose_name="Placa"),
                ),
                ("capacidad", models.CharField(max_length=7, verbose_name="Capacidad")),
                (
                    "conductor_id",
                    models.ForeignKey(
                        blank=True,
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehiculo_conductor_id",
                        to="conductoresApp.conductor",
                    ),
                ),
            ],
        ),
    ]
