# Generated by Django 4.2 on 2023-05-10 05:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("conductoresApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.PositiveIntegerField(
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.MaxValueValidator(
                                limit_value=999999999999,
                                message="Identificador fuera de los limites superiores",
                            ),
                            django.core.validators.MinValueValidator(
                                limit_value=1,
                                message="Identificador fuera de los limites inferiores",
                            ),
                        ],
                    ),
                ),
                ("tipo_pedido", models.CharField(max_length=20, verbose_name="Tipo")),
                (
                    "direccion",
                    models.CharField(max_length=50, verbose_name="Direccion"),
                ),
                (
                    "conductor_id",
                    models.ForeignKey(
                        blank=True,
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedido_conductor_id",
                        to="conductoresApp.conductor",
                    ),
                ),
            ],
        ),
    ]
