# Generated by Django 4.2 on 2023-05-10 05:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conductor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificacion",
                    models.PositiveIntegerField(
                        unique=True,
                        validators=[
                            django.core.validators.MaxValueValidator(
                                limit_value=99999999999,
                                message="Identificador fuera de los limites superiores",
                            ),
                            django.core.validators.MinValueValidator(
                                limit_value=1,
                                message="Identificador fuera de los limites inferiores",
                            ),
                        ],
                        verbose_name="Identificacion",
                    ),
                ),
                ("nombre", models.CharField(max_length=20, verbose_name="Nombre")),
                (
                    "apellido",
                    models.CharField(max_length=20, null=True, verbose_name="Apellido"),
                ),
                (
                    "telefono",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(
                                limit_value=99999999999,
                                message="Identificador fuera de los limites superiores",
                            ),
                            django.core.validators.MinValueValidator(
                                limit_value=1,
                                message="Identificador fuera de los limites inferiores",
                            ),
                        ],
                        verbose_name="Telefono",
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        max_length=50, null=True, unique=True, verbose_name="Direccion"
                    ),
                ),
            ],
        ),
    ]
